name: Enjoy Riviera Maya
favicon: null
layout_spectrum: 0.62647
typography_spectrum: 0.32025
title: 'Playa del Carmen Private Tours & Scuba Diving '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1aa1d8'
    - '#010101'
    - '#bdf7fe'
    - '#a95c5e'
    - '#b39d76'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
